finalBlog/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('my_posts', views.MyPostView.as_view(), name="my_posts"),
    path('post/<int:pk>', views.PostDetailView.as_view(), name="post_details"),
    path('post/<slug:slug>', views.TagIndexView.as_view(), name="tagged"),
    path('add_post/',views.AddPostView.as_view(),name="add_post"),
    path('post/edit/<int:pk>',views.UpdatePostView.as_view(),name="update_post"),
    path('post/delete/<int:pk>',views.DeletePostView.as_view(),name="delete_post"),
    path('like/<int:pk>', views.LikeView, name='like_post'),
    path('comment_like/<int:pk>', views.CommentLikeView, name='comment_like'),
    path('liked_posts/', views.LikedView.as_view(), name='liked_posts'),
    path('save/<int:pk>', views.SaveView, name='save_post'),
    path('saved_posts/', views.SavedView.as_view(), name='saved_posts'),
    #path('comment/<int:pk>', views.postComment, name='post_comment'),
    path('search/',views.search,name="search"),
]

finalBlog/finalBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header="Blog Admin"
admin.site.site_title="Blog Admin Panel"
admin.site.index_title="Welcome to Blog Admin Panel"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finalBlog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from datetime import datetime, date
from django_ckeditor_5.fields import CKEditor5Field
from hitcount.models import HitCountMixin, HitCount
from django.contrib.contenttypes.fields import GenericRelation
from taggit.managers import TaggableManager
from mptt.models import MPTTModel, TreeForeignKey 
from ckeditor.fields import RichTextField
# Create your models here.
class Post(models.Model):
	title = models.CharField(max_length=255)
	header_image = models.ImageField(null=True, blank=True, upload_to="images/")
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	#body = models.TextField()
	#body = CKEditor5Field('Text', config_name='extends')
	body = CKEditor5Field('Text', config_name='extends', blank=True)
	post_date = models.DateTimeField(auto_now_add=True, editable=False)
	update_date = models.DateTimeField(blank=True, null=True)
	likes = models.ManyToManyField(User, related_name='blog_posts')
	saved = models.ManyToManyField(User, related_name='save_posts')
	hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',related_query_name='hit_count_generic_relation')
	#slug = models.SlugField(max_length=255, blank=True,null=True)
	tags = TaggableManager()

	def total_likes(self):
		return self.likes.count()

	def liked_by(self):
		return self.likes.all()

	def __str__(self):
		return self.title + ' | ' + str(self.author)

	def get_absolute_url(self):
		#return reverse('post_details', args=(str(self.id)))
		return reverse('home')

	def update(self, *args, **kwargs):
		kwargs.update({'update_date': timezone.now})
		#super().update(*args, **kwargs)
		return self

# class Likes(models.Model):
# 	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_like')
# 	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_like')



class Profile(models.Model):
	user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
	bio = models.TextField()
	profile_pic = models.ImageField(null=True, blank=True, upload_to="images/profile")
	your_website = models.CharField(max_length=255, null=True, blank=True)
	fb = models.CharField(max_length=255, null=True, blank=True)
	linkedin = models.CharField(max_length=255, null=True, blank=True)
	insta = models.CharField(max_length=255, null=True, blank=True)
	twitter = models.CharField(max_length=255, null=True, blank=True)
	
	def __str__(self):
		return str(self.user)

	def get_absolute_url(self):
		#return reverse('post_details', args=(str(self.id)))
		return reverse('home')

class Comment(MPTTModel):
	#sno = models.AutoField(primary_key = True)
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='parent_comment')
	comment = models.TextField()
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	timestamp = models.DateTimeField(default=timezone.now)
	# publish = models.DateTimeField(auto_now_add=True)
	status = models.BooleanField(default=True)
	likes = models.ManyToManyField(User, related_name='commentlikes')

	class MPTTMeta:
		order_insertion_by = ['timestamp']

	def __str__(self):
		return self.comment[0:20] + '... by ' + str(self.user.username)

	def total_comments(self):
		return self.count()

finalBlog/blog/forms.py
from django import forms
from .models import Post, Comment
from ckeditor.widgets import CKEditorWidget
from ckeditor.fields import RichTextFormField
from mptt.forms import TreeNodeChoiceField

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('title', 'author', 'body','tags')
		body = forms.CharField(widget=CKEditorWidget(attrs={'class':'form-control', 'required':'false'}))

		widgets = {
			'title':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter the title of the blog here'}),
			'author':forms.TextInput(attrs={'class':'form-control','value':'', 'id':'sanya', 'type':'hidden'}),
			'tags':forms.TextInput(attrs={'class':'form-control','data-role':'tagsinput','name':'tags'}),
			#'body':forms.CharField(widget=CKEditorWidget(attrs={'class':'form-control'})),
			#'author':forms.Select(attrs={'class':'form-control'}),
			#'body':forms.Textarea(attrs={'class':'form-control', 'placeholder':'Start writing your blog'}),
		}

class EditForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('title', 'body')

		widgets = {
			'title':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter the title of the blog here'}),
			'body':forms.Textarea(attrs={'class':'form-control', 'placeholder':'Start writing your blog'}),
			#'tags':forms.TextInput(attrs={'class':'form-control','data-role':'tagsinput'}),
		}

# class CommentForm(forms.ModelForm):
# 	class Meta:
# 		model = Comment
# 		fields = ('comment', 'postSno')

# 		widgets = {
# 			'comments':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your comment'}),
# 			'postSno':forms.IntegerField(attrs={'class':'form-control','value':'{{ post.sno }}', 'type':'hidden'}),
# 		}

class NewCommentForm(forms.ModelForm):
	parent = TreeNodeChoiceField(queryset=Comment.objects.all())

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['parent'].widget.attrs.update({'class': 'd-none'})
		self.fields['parent'].label = ''
		self.fields['parent'].required = False

	class Meta:
		model = Comment
		fields = ('parent','comment')
		widgets = {
			'comment': forms.Textarea(attrs={'class': 'form-control'}),
	        }
	def save(self, *args, **kwargs):
		Comment.objects.rebuild()
		return super(NewCommentForm, self).save(*args, **kwargs)

finalBlog/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, edit
from .models import Post, Comment
from .forms import PostForm, EditForm, NewCommentForm
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from blog.templatetags import extras
from django.utils import timezone
from hitcount.views import HitCountDetailView
from django.db.models import Q


class TagMixin(object):
	def get_context_data(self,**kwargs):
		context = super(TagMixin, self).get_context_data(**kwargs)
		context['tags'] = Post.tags.all()
		return context

class HomeView(TagMixin, ListView):
	model = Post
	template_name = 'home.html'
	ordering = ['-post_date']
	#ordering = ['-id']

	# def get_context_data(self, **kwargs):
	# 	context = super(HomeView, self).get_context_data(**kwargs)
	# 	context.update({
	# 		'popular_posts': Post.objects.order_by('-hit_count_generic')[:3],
	# 		})
	# 	return context

class TagIndexView(TagMixin, ListView):
	template_name = 'home.html'
	model = Post

	def get_queryset(self):
		return Post.objects.filter(tags__slug=self.kwargs.get('slug'))

class MyPostView(ListView):
	model = Post
	template_name = 'my_posts.html'
	ordering = ['-post_date']

class PostDetailView(edit.FormMixin, HitCountDetailView):
	model = Post
	template_name = 'post_details.html'
	context_object_name = 'post'
	count_hit = True
	form_class = NewCommentForm


	def post(self, *args, **kwargs):
		stuff = get_object_or_404(Post, id=self.kwargs['pk'])
		comments = Comment.objects.filter(post=stuff, status=True)
		user_comment = None

		if self.request.method == 'POST':
			comment_form = self.get_form()
			if comment_form.is_valid():
				user_comment = comment_form.save(commit=False)
				user_comment.post = stuff
				user_comment.user = self.request.user
				user_comment.save()
				return HttpResponseRedirect(self.request.path_info)
		else:
			comment_form = self.get_form()
		return HttpResponseRedirect(self.request.path_info)


	def get_context_data(self, *args, **kwargs):
		context = super(PostDetailView, self).get_context_data(**kwargs)
		stuff = get_object_or_404(Post, id=self.kwargs['pk'])
		total_likes = stuff.total_likes()

		liked = False
		if stuff.likes.filter(id=self.request.user.id).exists():
			liked = True

		saved = False
		if stuff.saved.filter(id=self.request.user.id).exists():
			saved = True

		comments = Comment.objects.filter(post=stuff, status=True)	
		context["total_likes"] = total_likes
		context["liked"] = liked
		context["saved"] = saved
		context["comments"] = comments
		context["comment_form"] = self.get_form()
		return context

class AddPostView(CreateView):
	model = Post
	form_class = PostForm
	template_name = 'add_post.html'
	#fields = '__all__'

class UpdatePostView(UpdateView):
	model = Post
	form_class = EditForm
	template_name = 'update_post.html'

	def get_object(self):
		obj = super().get_object()
		# Record the last accessed date
		obj.update_date = timezone.now()
		obj.save()
		return obj

	# def get_context_data(self, *args, **kwargs):
	# 	context = super(UpdatePostView, self).get_context_data(**kwargs)
	# 	stuff = get_object_or_404(Post, id=self.kwargs['pk'])
	# 	update_time = stuff.update()
	# 	context['update_time'] = update_time


class DeletePostView(DeleteView):
	model = Post
	template_name = 'delete_post.html'
	success_url = reverse_lazy('home')

class LikedView(ListView):
	model = Post
	template_name = 'liked_posts.html'

class SavedView(ListView):
	model = Post
	template_name = 'saved_posts.html'

	# def get_context_data(self, *args, **kwargs):
	# 	context = super(LikedView, self).get_context_data(**kwargs)
	# 	stuff = get_object_or_404(Post)
	# 	liked='c'
	# 	if stuff.likes.filter(id=self.request.user.id).exists():
	# 		liked = self.request.user.id
	# 	context["liked"] = liked
	# 	return context

def CommentLikeView(request, pk):
	comment = get_object_or_404(Comment, id=request.POST.get('commentt_id'))
	liked = False
	if comment.likes.filter(id=request.user.id).exists():
		comment.likes.remove(request.user)
		liked = False
	else:
		comment.likes.add(request.user)
		liked = True
	return HttpResponseRedirect(reverse('post_details', args=[str(comment.post.id)]))

def LikeView(request, pk):
	post = get_object_or_404(Post, id=request.POST.get('post_id'))
	liked = False
	if post.likes.filter(id=request.user.id).exists():
		post.likes.remove(request.user)
		liked = False
	else:
		post.likes.add(request.user)
		liked = True
	return HttpResponseRedirect(reverse('post_details', args=[str(pk)]))

def SaveView(request, pk):
	post = get_object_or_404(Post, id=request.POST.get('post_id'))
	saved = False
	if post.saved.filter(id=request.user.id).exists():
		post.saved.remove(request.user)
		saved = False
	else:
		post.saved.add(request.user)
		saved = True
	return HttpResponseRedirect(reverse('post_details', args=[str(pk)]))


# def postComment(request, pk):
# 	# if request.method=="POST":
# 	# 	comment = request.POST.get("comment")
# 	# 	user = request.user
# 	# 	postSno = request.POST.get("postSno")
# 	# 	post = get_object_or_404(Post, id=request.POST.get('postSno'))
# 	# 	parentSno = request.POST.get("parentSno")
# 	# 	if parentSno == None:
# 	# 		comment = Comment(comment=comment, user=user, post=post)
# 	# 		comment.save()
# 	# 		messages.success(request,"Your comment has been posted successfully!")
# 	# 	else:
# 	# 		parent = Comment.objects.get(sno = parentSno)
# 	# 		comment = Comment(comment=comment, user=user, post=post, parent=parent)
# 	# 		comment.save()
# 	# 		messages.success(request,"Your Reply has been posted successfully!")
# 	# return HttpResponseRedirect(reverse('post_details', args=[str(pk)]))
# 	post = get_object_or_404(Post, id=request.POST.get('post_id'))
# 	comments = Comment.objects.filter(post=post, status=True)
# 	user_comment = None

# 	if request.method == 'POST':
# 		comment_form = NewCommentForm(request.POST)
# 		if comment_form.is_valid():
# 			user_comment = comment_form.save(commit=False)
# 			user_comment.post = post
# 			user_comment.save()
# 			return HttpResponseRedirect(reverse('post_details', args=[str(pk)]))
# 	else:
# 		comment_form = NewCommentForm()
# 	return render(request, 'post_details.html', {'post': post, 'comments':  user_comment, 'comments': comments, 'comment_form': comment_form})

def search(request):
	querys = request.GET.get('query').split()
	query = Q()
	for word in querys:
		query = query | Q(title__icontains=word) | Q(author__first_name__icontains=word) | Q(author__last_name__icontains=word) | Q(author__username__icontains=word) | Q(body__icontains=word) | Q(tags__name__icontains=word)
	results = Post.objects.filter(query).distinct()
	params = {'allPost': results}
	return render(request, 'search.html', params)
	# titles = Post.objects.filter(title__icontains=query)
	#tags = Post.objects.filter(tags__icontains=query)
	# first = Post.objects.filter(author__first_name__icontains=query)
	# last = Post.objects.filter(author__last_name__icontains=query)
	# username = Post.objects.filter(author__username__icontains=query)
	# body = Post.objects.filter(body__icontains=query)
	# search = titles.union(body,first,last,username)
	
	#return HttpResponse('This is search')
# def MyLikedPostView(request):
# 	post = get_object_or_404(Post)
# 	context={}
# 	l=[]
# 	for i in post:
# 		if i.likes.filter(id=request.user.id).exists():
# 			l.append(request.user.username)
# 	context['post_liked'] = l
# 	return render(request, 'liked_posts.html', context)


# def LikedView(request, pk):
# 	post = get_object_or_404(Post, id=request.POST.get('post_id'))
# 	l=[]
# 	if post.likes.filter(id=request.user.id).exists():
# 		l.append(post)
		
# 	return HttpResponseRedirect(reverse('post_details', args=[str(pk)]))


# class LikedView(ListView):
# 	model = Post
# 	template_name = 'liked_posts.html'

# 	def get_context_data(self, *args, **kwargs):
# 		context = super(LikedView, self).get_context_data(**kwargs)
# 		l=[]
# 		for i in get_object_or_404(Post).likes.filter(id=self.request.user.id):
# 			l.append(i)
		

# 		context["posts"] = l
# 		return context

# def post_likes(request, pk):
#     posts = Post.objects.all()
#     post_likes = posts.likes.all()
#     context = {'post_likes': post_likes,}
#     return render(request, 'liked_posts.html', context)

		

finalBlog/blog/templates/add_post.html
{% extends 'base.html' %}
{% block title %}
Create a new blog post
{% endblock %}
{% block extrahead %}
<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
{{ block.super }}
{% endblock %}
{% block content %}
{% if user.is_authenticated %}
<h1>Add Blog Post</h1>
<br/><br/>
<div class="form-group">
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	{{ form.media }}
	<button class="btn btn-secondary">
		Post
	</button>
</form>
</div>
<script>
	var name = "{{ user.id }}";
	document.getElementById('sanya').value = name;
</script>
{% else %}
You are not logged in!
{% endif %}
{% endblock %}

finalBlog/blog/templates/delete_post.html
{% extends 'base.html' %}
{% block title %}
Delete blog post
{% endblock %}
{% block content %}
{% if user.is_authenticated %}
{% if user.id == post.author.id %}
<h1>Delete Post</h1>
<br/><br/>
<h3>Delete: {{ post.title }}</h3>
<div class="form-group">
<form method="POST">
	{% csrf_token %}
	<strong>Are you sure?</strong>
	<br/><br/>
	<button class="btn btn-secondary">
		Delete Post!
	</button>
	<a href="{% url 'home' %}" class="btn btn-secondary">Back</a>
</form>
</div>
{% else %}
You are not the author of the Post
{% endif %}
{% else %}
You are not logged in!
{% endif %}
{% endblock %}

finalBlog/blog/templates/post_details.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load extras %}
{% load hitcount_tags %}
{% block title %}
{{ post.title }}
{% endblock %}
{% block content %}
<div class="container">
<h1>{{ post.title }}</h1>
<small><i class="fa fa-pencil" aria-hidden="true"></i> {{ post.author.first_name }} {{ post.author.last_name }} <br>
<i class="fa fa-clock-o" aria-hidden="true"></i> {{ post.post_date}} IST</small>
{% if post.update_date == None %}
{% else %}
<small> <i class="fa fa-wrench" aria-hidden="true"></i> {{ post.update_date | naturaltime }}</small>
{% endif %}
<br>
<small><i class="fa fa-eye" aria-hidden="true"></i> {% get_hit_count for post %}</small><br>
<small><i class="fa fa-book" aria-hidden="true"></i> {{ post.body|readtime }}</small>
<hr>
<br/>
{% if post.header_image %}
{{ post.header_image.url }}
<img src="{{ post.header_image.url }}">
{% endif %}
{{ post.body|safe }}
<br/>
<br/>
{% if user.is_authenticated %}
{% if user.id == post.author.id %}
<a href="{% url 'update_post' post.pk %}" class="btn btn-secondary">Edit</a>
<a href="{% url 'delete_post' post.pk %}" class="btn btn-secondary">Delete</a>
{% endif %}
<a href="{% url 'home' %}" class="btn btn-secondary">Home</a>
<br/><br/>
<hr>
<br/>
{% endif %}
<form action="{% url 'like_post' post.pk %}" method="POST">
	{% csrf_token %}
	{% if user.is_authenticated %}
	{% if liked %}
	<button type="submit", name="post_id", value="{{ post.id }}">
		unlike
	</button><small>->{{ total_likes }}</small>
	{% else %}
	<span>liked!</span>
	<button type="submit", name="post_id", value="{{ post.id }}">
		like
	</button><small>->{{ total_likes }}</small>
	{% endif %}
	{% else %}
	<small><a href="{% url 'login' %}">login</a> to like</small>
	{% endif %}
  <!--<i class="far fa-heart"></i>
  <i class="fas fa-heart"></i>-->
</form> 
<form action="{% url 'save_post' post.pk %}" method="POST">
  {% csrf_token %}
  {% if user.is_authenticated %}
  {% if saved %}
  <button type="submit", name="post_id", value="{{ post.id }}">
    unsave
  </button>
  {% else %}
  <span>Saved!</span>
  <button type="submit", name="post_id", value="{{ post.id }}">
    save
  </button>
  {% endif %}
  {% else %}
  <small><a href="{% url 'login' %}">login</a> to save</small>
  {% endif %}
</form> 
 <br><br>
 <p>Liked by:</p>
{% for u in post.likes.all %}
<a href="{% url 'profile_page' u.profile.id %}">{{ u }}</a><br>
{% endfor %}
<div class="card mb-3">
  <div class="row no-gutters">
    <div class="col-md-2">
    	{% if post.author.profile.profile_pic %}
      <img src="{{ post.author.profile.profile_pic.url }}" class="card-img" alt="..." width="200" height="200">
      {% else %}
       <img src="{% static 'blog/images/no_profile_pic.jpg' %}" class="card-img" alt="..."width="200" height="200">
      {% endif %}
    </div>
    <div class="col-md-10">
      <div class="card-body">
        <h5 class="card-title">{{ post.author.first_name }} {{ post.author.last_name }} </h5>
        <p class="small text-muted">
          <a href="{% url 'profile_page' post.author.profile.id %}">Profile Page</a> |
        	{% if post.author.profile.your_website %}
        	<a href="{{ post.author.profile.your_website }}">Website</a> |
        	{% endif %}

        	{% if post.author.profile.linkedin %}
        	<a href="{{ post.author.profile.linkedin }}">Linkedin</a> |
        	{% endif %}

        	{% if post.author.profile.twitter %}
        	<a href="{{ post.author.profile.twitter }}">Twitter</a> |
        	{% endif %}

        	{% if post.author.profile.fb %}
        	<a href="{{ post.author.profile.fb }}">Facebook</a> |
        	{% endif %}

        	{% if post.author.profile.insta %}
        	<a href="{{ post.author.profile.insta }}">Instagram</a> |
        	{% endif %}

        </p>
        <p class="card-text">{{ post.author.profile.bio }}</p>
      </div>
    </div>
  </div>
</div>
<div class="container">
 <div class="col-md-7">

              {% load mptt_tags %}
              <div>
                {% recursetree comments %}
                <div id="{{ node.id }}"> <b>{{ node.user.first_name }} {{ node.user.last_name }}</b> <small>{{ node.timestamp|naturaltime }}</small><br>{{ node.comment }}<br>
 </div>
  <form action="{% url 'comment_like' node.id %}" method="POST">
  {% csrf_token %}
  {% if user.is_authenticated %}
  {% if liked %}
  <button type="submit", name="commentt_id", value="{{ node.id }}">
    thumb down
  </button><small>->{{ node.likes.count }}</small>
  {% else %}
  <button type="submit", name="commentt_id", value="{{ node.id }}">
    thumbs up
  </button><small>->{{ node.likes.count }}</small>
  {% endif %}
  {% else %}
  <small><a href="{% url 'login' %}">login</a> to like</small>
  {% endif %}
</form> 
                <button class="button" onclick="myFunction( {{ node.id }} )">Reply</button>
                <hr>

                {% if not node.is_leaf_node %}
                <div class="children pl-2 pl-md-5">
                  {{ children }}
                </div>
                {% endif %}
                {% endrecursetree %}
              </div>
                <h2>Make a new comment</h2>

              <div class="form-group">
              <form method="POST" id="myForm"> <!-- action="{% url 'post_details' post.pk %}"> --> 
                {{ comment_form.as_p }}
                {% csrf_token %}
                <button class="btn btn-secondary">
                  Submit
                </button>
              </form>
              </div>

          </div>
        </div>
      </div>
    </div>
  <br>
</div>

</div>
</div>
</div>

</div>
<script>
  function formExit() {
    document.getElementById("newForm").remove();
  }

  function myFunction(id) {
    if (document.contains(document.getElementById("newForm"))) {
      document.getElementById("newForm").remove();
    }

    var d1 = document.getElementById(id);
    d1.insertAdjacentHTML('afterend',
      '<form id="newForm" class="form-insert py-2" method="post"> \
      {% csrf_token %} \
      <div class="d-flex justify-content-between"><h2>Reply:</h2><div><button type="button" class="btn btn-outline-secondary" onclick="formExit()"">Close</button></div></div> \
      <label for="id_comment">Content:</label> \
      <textarea name="comment" cols="40" rows="5" class="form-control" required id="id_content"></textarea> \<select name="parent" class="d-none" id="parent"> \
      <option value="' + id + '" selected="' + id + '"></option> </select> \
      <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button> \
      </form>');

    //document.querySelector('#id_parentt [value="' + id + '"]').selected = true;
  }

  $('#myForm').trigger("reset");
</script>
<!-- <script>
  function myFunction(id){
    var a = document.getElementById(id);
    a.insertAdjacentHTML('afterend', 
      "<form method="POST" id="myForm">\
      <p> <select name="parent" class="d-none" id="id_parentt">\
      <option value="' + id + '" selected="' + id + '"></option>\
      </select></p>\
      <p><label for="id_comment">Comment:</label> <textarea name="comment" cols="40" rows="10" class="form-control" required="" id="id_comment"></textarea></p>\
      {% csrf_token %}\
      <button class="btn btn-secondary">Submit</button>\
      </form>");
  }
</script> -->
</div>
{% endblock %}

finalBlog/blog/templates/search.html
{% extends 'base.html' %}
{% load hitcount_tags %}
{% load extras %}
{% block content %}
<div class="container">
<h1>Search Results:</h1>
<ul style="list-style-type: none;">
{% for post in allPost %}
<li>
<a href="{% url 'post_details' post.pk %}">{{ post.title }}</a> - <small>{{ post.author.first_name}} {{ post.author.last_name}} | {{ post.post_date }} IST | Views: {% get_hit_count for post %} | {{ post.body|readtime }}</small><br>{{ post.body|safe|truncatewords:30}} <a href="{% url 'post_details' post.pk %}">Read more</a> </li>
{% if user.is_authenticated %}
{% if user.id == post.author.id %}
<small><a href="{% url 'update_post' post.pk %}">Edit</a></small>
<small><a href="{% url 'delete_post' post.pk %}">Delete</a></small>
{% endif %}
{% endif %}
{% empty %}
No Results found 
<br/><br/>
{% endfor %}
</ul>
</div>
{% endblock %}

finalBlog/blog/templates/update_post.html
{% extends 'base.html' %}
{% block title %}
Edit blog post
{% endblock %}
{% block content %}
{% if user.is_authenticated %}
{% if user.id == post.author.id %}
<h1>Update Blog Post</h1>
<br/><br/>
<div class="form-group">
<form method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	{{ form.media }}
	<button class="btn btn-secondary">
		Update
	</button>
</form>
</div>
{% else %}
You are not the author of the Post
{% endif %}
{% else %}
You are not logged in!
{% endif %}
{% endblock %}